### ISSUE TITLE
Mobile Responsive 

### ISSUE THREAD

**Issue by mellofordev** [mellofordev/internshipcell#1]
Needed to make the site more mobile responsive

**Comment by Arsh-a** [comment]
> Needed to make the site more mobile responsive 
> 

I wud like to contribute to this web page

**Comment by mellofordev** [comment]
Assigned ⚡
btw i made some of the sections of the site responsive...

**Comment by mellofordev** [comment]
Closed this issue with commit 8a0f04d8fa53fb4e432b347ae08b1836e42b7637
Also removed the assigne due to no pull request
