### ISSUE TITLE
Add animation to the topnav viewer 

### ISSUE THREAD

**Issue by mellofordev** [mellofordev/internshipcell#2]
Add an animation to the topviewer 
Animation details :
1.when user clicks on the hamburger button the topnav viewer should pop-in to the screen from top in a linear format 
2.Time-duration is 5s max

**Comment by JanitaRiyaz** [comment]
i wanna do this. Assign thisto me.

**Comment by JanitaRiyaz** [comment]
i wanna do this. Assign this to me.

**Comment by mellofordev** [comment]
Closing this  issue as it is fixed with commit 334bbc8a56aa8c7346ae96d585c4e013aa7a12ff
