### ISSUE TITLE
Design the Gallery section

### ISSUE THREAD

**Issue by mellofordev** [mellofordev/internshipcell#3]
Design the Gallery section 
Details:
1.Images can be random
2.Grid view/horizontal scroll

**Comment by AkarshAnilkumar** [comment]
Hi Sreedhar, 
      I would like to contribute to this webpage.

**Comment by mellofordev** [comment]
Assigned ⚡

**Comment by mellofordev** [comment]
Unassigning @AkarshAnilkumar due to no pull request
